### ISSUE TITLE
Conversation Mode / Insert mode

### ISSUE THREAD

**Issue by pinpox** [mcpcpc/kirc#10]
**Is your feature request related to a problem? Please describe.**
I find it a bit tedious to type  `:m` every time I want to send a message, especially when conversating/writing back and forth with a person.

**Describe the solution you'd like**
Add some functionality equivalent to Vim's insert mode. It would be nice to have `typing`+`enter` just send a message, until `escape` is pressed. That way when chatting with a person or channel you could "just type". While in vim it makes sense to stay as long as possible in command mode, typing and reading messages is the primary usecase for a chatclient with commands being the exception.

**Comment by mcpcpc** [comment]
I think this is a really good suggestion! i would definitely agree that `:m ` is a bit cumbersome, requiring 5 keystrokes (if you include the spacebar, shift key and return key to send the command).  

In addition to your suggestion, here are a couple other ideas that come to mind that could simplify things:

## Option 1: Replace `:` character with an alternative leader character (e.g. `/`).

Example:

```
/m <message>
```
This is the simplest change of the options.  the disadvantage is that any other key might be confusing to anyone used to using vim.

## Option 2: Same as Option 1 but remove the `m` command character as well.

Example:

```
/ <message>
```

This option is nice since it requires 2 fewer keystrokes. The disadvantages are the same as option 1. 

## Option 3: Remove the `m` command key and send commands with just the leader key, `:`.  

Example:

```
: <message>
```

1 less keystroke and probably the option i would “lean” towards as it’s still “familiar” to vim users. 

## Option 4: One of the first 3 options, plus the option to set custom leader and/or command keys.  

Every user will have their own set of preferred key presses and, in today’s worlds, customization is king.  Not sure if i am a big fan of this though.  

## Option 5: Create a true vi-like modal input (e.g INSERT mode).  

Probably the most challenging of the options as this requires leaving *canonical* mode for *raw* mode And creating a custom text editor.  I attempted this a week back, but was not successful as the behavior was not consistent across terminals. From what i have read, the `ncurses` library could be used to simplify things but, as far as i am aware, is not part of the POSIX standard. 

This solution also best aligns with the original proposed solution since it’s easiest to customize key functionality (e.g. ESC key to return `stdin`) from *raw* mode.  

## Option 6: Remove the leader key and command key all together for regular channel messages.  

Example:

```
<message>
```

3 fewer key strokes. the only issue here is that we loose the ability to distinguish intentional keystrokes from accidental keystrokes.

**Comment by pinpox** [comment]
Thanks for looking into this. I feel like it would be a feature that would make it truly usable.

If implementing a real INSERT mode is too difficult, I would go with the last option if dropping commands all together or have everything that does not start with a / character be a normal message.

With the last option you would just type the message and press enter, but "messages" staring with / would be a command like in other irc clients (e.g. /join, /leave, /nick etc.)

**Comment by mcpcpc** [comment]
I agree with your assessment.  Also I don’t see “true” modal input as an impossibility, but rather it will take some time to implement correctly. Let’s try for *Option 6* and see how it goes.  This will also “force” me to fix an unusual behavior where the first character of `stdin` is unable to be deleted.  :)

**Comment by mcpcpc** [comment]
**Update**: Created the following [branch](https://github.com/mcpcpc/kirc/tree/simplified_cmds) to test the new command style out.  As of https://github.com/mcpcpc/kirc/commit/a9a9093d935b7b19ea9e5e92d79b39f3d58f500d, you should be able to issue the following IRC commands using the new `/` leader character and send messages to the channel without requiring a command character.  this should allow for easier direct messages:

```
  <message>                   send a message to the connected channel
  /M <nick|channel> <message> send a message to a specified nick or channel
  /n <message>                send a message to NickServ
  /j <channel>                join a specified channel
  /p <channel>                leave a specified channel
  /Q <message>                send a message and close the host connection
  /q                          close the host connection
```

One last annoying issue to figure out... once a message or command is started, the user is unable to erase the initial character.

**Comment by mcpcpc** [comment]
Fixed the issue with deletion of the initial message character (see https://github.com/mcpcpc/kirc/commit/ecc8e880970d7528b5d745e2dba3a9c7eccef1d0).  I while i test out the new command functionality over the next few days before merging to the master branch.  If all goes well, i will promote to 0.0.7 release and close this issue for now.

**Comment by pinpox** [comment]
Great work, much appreciated! Will test aus the branch tomorrow

**Comment by mcpcpc** [comment]
Merged into master (https://github.com/mcpcpc/kirc/pull/11)
