### ISSUE TITLE
text wrapping bug

### ISSUE THREAD

**Issue by mcpcpc** [mcpcpc/kirc#117]
as reported on #kisslinux by @kyxor:

> <kyxor> you do guys ever get a bug in kirc when you reach the end of terminal window size, the text starts to wrap to new lines and displays corrupted symbols. doesn't always happen, probably depends on the last character

https://0x0.st/-O3g.png

**Comment by kyx0r** [comment]
@mcpcpc just in case you don't see on irc, I fixed it - https://0x0.st/-Odx.patch

It may not be final cause I have to text it good, but it works.

**Comment by kyx0r** [comment]
@mcpcpc Sorry, I didn't test the utf-8 properly, but I fix.

Try this patch now: https://0x0.st/-Odn.patch

**Comment by mcpcpc** [comment]
thanks!

**Comment by kyx0r** [comment]
@mcpcpc mcpcpc_: you applied the wrong patch :( I am sorry first version has messed up utf-8 chars, please reapply this one: https://0x0.st/-Odn.patch

The difference is in "txtlenb += u8Next(buf+txtlenb, 0);" has to have +txtlenb because we want to iterate over the chars, in the first patch it does not

**Comment by mcpcpc** [comment]
Errr my bad. Fixed! Thanks again =)
