### ISSUE TITLE
what is the difference between ii and kirc?

### ISSUE THREAD

**Issue by johsjohsjohs** [mcpcpc/kirc#128]
like the title says what is the difference between [ii](https://tools.suckless.org/ii/) kirc?

**Comment by mcpcpc** [comment]
> like the title says what is the difference between [ii](https://tools.suckless.org/ii/) kirc?

There are many differences!  It’s been a while since i compared the two, but to name a few... 
* `ii` uses a file-based buffering system while `kirc` buffers in ram. 
* Both clients are fairly minimal; however, `ii` is more fully featured, especially w.r.t. multi-channel support
* From a UI perspective, you will find `ii` difficult to use alone without a wrapper script.  `kirc` is intended to be standalone and has a built-in minimal text editor with input history buffer.  

Overall, i would say try both and see what best suits your needs.  Also, let know if there is anything specific you would like me to elaborate on ;).
