### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by 097115** [mcpcpc/kirc#67]
**Describe the bug**

Exits with `connection closed` after some inactivity

**To Reproduce**

1. Launch `kirc`, connect so some server, join some channel
2. Make the prompt appear by e.g. pressing the Up arrow
3. Do nothing for some 10 minutes (5 is not enough, really :)
4. Press Enter (or you can type any command here, like `/time`), observe `kirc` quitting with `connection closed` instead of just getting an expected reply from a server,`No text to send`

**Desktop (please complete the following information):**

 - Linux, macOS
 - kirc-0.1.6 (5c6c123)
 - Tested both with undernet.org and freenode.net, both secure and insecure connections.

**Comment by mcpcpc** [comment]
This is the current **expected** functionality of kirc since user input is a blocking function.  This means server message handling (i.e. automatic keep-alive/PING response or new received messages) cannot be performed while in "user input mode" until user presses Enter/Return. Ultimately, the server connection times out and closes. 

Consequently, I am working to implement an asynchronous version of the input handling function (see issue https://github.com/mcpcpc/kirc/issues/66) which should address this "adverse behavior" going forward.

I will leave this open until https://github.com/mcpcpc/kirc/issues/66 is resolved.

**Comment by 097115** [comment]
Thanks for the explanation!

**Comment by mcpcpc** [comment]
@097115 : 0.1.7 (via https://github.com/mcpcpc/kirc/pull/68) is ready to be merged. Would you be able to test this branch to make sure that it addresses your concern?

**Comment by 097115** [comment]
@mcpcpc Seems to be working fine, thank you!
