### ISSUE TITLE
Support for CTCP commands

### ISSUE THREAD

**Issue by kdkasad** [mcpcpc/kirc#80]
There are a few CTCP (client-to-client protocol) commands that are used frequently in IRC. The most useful/common are:
- `VERSION`
- `PING`
- `ACTION`
- `CLIENTINFO`

It would be great if `kirc` supported these.

I've added support for them in my fork, but since I'm nowhere near as good at C programming as @mcpcpc, I expect there's a much more elegant solution:
https://git.kasad.com/kirc/log/?h=devel

**Comment by mcpcpc** [comment]
@kdkasad https://github.com/mcpcpc/kirc/pull/79 is ready to be merged with the CTCP commands.  It’s mostly based on your implementation, although I have not tested it yet (need to do some more reading on CTCP first).

**Comment by kdkasad** [comment]
I can do some testing. I looked through the code and it seems like it should be fine. I didn't implement the `TIME` command, which according to [the spec](https://tools.ietf.org/id/draft-oakley-irc-ctcp-01.html#rfc.appendix.A.7) should be implemented.

**Comment by mcpcpc** [comment]
> I can do some testing. I looked through the code and it seems like it should be fine. I didn't implement the `TIME` command, which according to [the spec].

Would appreciate the testing.  Also, added the CPCT `TIME` command.

**Comment by kdkasad** [comment]
`ACTION`, `VERSION`, `CLIENTINFO`, and `PING` work. `TIME` does not.

I think the problem is that the raw response command should be:
```
NOTICE <source nick> :\001TIME <current time>\001\r\n
```
Currently it is:
```
NOTICE <source nick> :\001<current time>\001\r\n
```

I also added support for sending the `ACTION` CTCP command using the `/me` command, as is standard in most clients:  
https://git.kasad.com/kirc/commit/?id=16b98708eace1ce3c6f931199687940d3cbb1bfd

**Comment by mcpcpc** [comment]
Fixed the syntax for the time command (https://github.com/mcpcpc/kirc/commit/fc2470248daaac69bd476233ccfd1697d4473cac).

> Although I wonder if it would be better to handle that differently so it works when using the `@<#channel|nick>` command, not just the default channel.

Added the equivalent `/me` command alias as `@@` (https://github.com/mcpcpc/kirc/commit/223d2e5c9ec26648c7a45c86ebcd48b4fc75fb9d).  Let me know your thoughts.

**Comment by kdkasad** [comment]
Looks good. It might be nice to make that work for private messages, too, but I think that would require duplicating code or creating another function. I'll see if I can find a nice way to do it.

**Comment by kdkasad** [comment]
After using it for a bit, I think it would be good to change the color of the nick which sends an ACTION command. It's impossible to tell the difference between a normal message and an ACTION, especially when the message is sent to the non-default channel.

**Comment by mcpcpc** [comment]
looking a little bit more at CTCP, i think just implementing the /me equivalent command alias might be too limiting. Instead, a generic ACTION privmsg should be preferred (i.e. `@@mcpcpc waves fist!` or `@@#archlinux waves fist`.  Ultimately, more characters to type, but helps keep the custom command aliases down.  Open to a counter argument though.  

Also, regarding color coding the nick to help identify ACTION messages received might not be the best idea.  For a new users, this might be confusing since there is no explanation to what specific colors mean. As kirc should be intuitive as possible, it might make more sense to prefix each message with the protocol type.  

Will play around with it a bit.  still trying to figure out which looks the cleanest and most intuitive.

**Comment by mcpcpc** [comment]
Pushed https://github.com/mcpcpc/kirc/commit/9525bb837e62446b62e139eae0b3909718986e67 for now.  Command structure is as previously described and all `ACTION` messages now are prefixed in the message.  Still not 100% pleased with it, but i think it’s a good start.
